name: example
description: "Flexbox Example App demonstrating flexbox layout capabilities."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flexbox_layout:
    path: ../
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  easy_refresh: ^3.4.0
  f_limit: ^1.1.0
  path: ^1.9.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cats/
