name: flexbox
description: >-
  A Flutter library for CSS Flexbox layout. Provides widgets for creating layouts
  using the CSS Flexbox layout model, bringing the power and flexibility of
  flexbox to Flutter.
version: 1.0.0
homepage: https://github.com/fluttercandies/flexbox
repository: https://github.com/fluttercandies/flexbox
issue_tracker: https://github.com/fluttercandies/flexbox/issues
documentation: https://github.com/fluttercandies/flexbox#readme

topics:
  - ui
  - widgets
  - layout
  - flexbox
  - css

environment:
  sdk: ^3.0.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  extended_list_library: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
